### ISSUE TITLE
Broken tables in aard

### ISSUE THREAD

**Issue by bkuhls** [itkach/mwscrape2slob#12]
Hi,
while comparing two revisions of mwscrape2slob/mw2slob I found that slob archives created with mw2slob contain broken tables, only the right half of the tables are visible in aard 0.53:

working revision: https://github.com/itkach/mw2slob/tree/e01d3e92f0a372ebd0f57390e437a28f9d3c0438 - screenshot: ![Screenshot_20220531-183147_Aard_2](https://user-images.githubusercontent.com/6279926/171227747-de87216a-3bc1-4ba7-bad9-e4cea186d2ae.png)

broken revision: https://github.com/itkach/mw2slob/tree/0358818432fc1404ce2ef7d35da7a59d970b77ef - screenshot: ![Screenshot_20220531-183214_Aard_2](https://user-images.githubusercontent.com/6279926/171227792-00cde644-4469-4ade-a1b4-05ffd8fc7cd9.png)
 
The slob archives were created from a local CouchDB server using these options:
```
-f common wiki -c lzma2 -ll en,nl,pl
```

**Comment by MHBraun** [comment]
I get the same result as with broken revision using the Enterprise dumps from wikimedia:
 
mw2slob dump -a $name -b $binsize -c lzma2 -o $out.slob --site-info $site.si.json $in.tar.gz -f wiki common

**Comment by itkach** [comment]
It's not tables in general, actually it's not about tables at all: it's infoboxes, when their content is too wide for the phone screen. I think the "culprit" [is this recently added CSS rule](https://github.com/itkach/mw2slob/blob/9d54f92fbdc7b80b42b308c144a1826a3dd44588/mw2slob/css/mediawiki_shared.css#L337) setting infobox width to `%100` on a narrow screen. This makes most infoboxes look nice on a phone screen, but the ones that are too wide get their left side chopped off. You can still see the entire infobox if you turn your phone to landscape orientation. Taking out `%100` width style may be one approach, but I like the way vast majority of infoboxes looks with it, so I'm reluctant to take it... I'm open to other suggestions :)

**Comment by MHBraun** [comment]
Thank you for checking, Igor. 
In landscape the box in the given example does not fit into the window either. But we can move it left and right to read the content, which is a work around.
Isn't there a possiblilty to read the screen width and then to adopt the size of the infobox to the screen. 
Downside of this would be that in really large info boxes the content would not be readable anymore. But then we could flip to landscape. Or we have a version of the infobox which is zoomable...

**Comment by MHBraun** [comment]
Actually, I figured that in landscape the info box IS zoomable to screen width. Would be nice to have this in portrait as well, but this is a good solution for me.

**Comment by itkach** [comment]
@bkuhls @MHBraun @Shudushi  Try with [this CSS](https://gist.github.com/itkach/1eb0fbe7e65e8acc9d3c35b0e0b14851). This is based on current Wikipedia mobile style. It turns off floating for infobox and tables on narrow screen, so nothing should be cut off. Wide tables inside infobox are made to scroll horizontally, which is not ideal because it interferes with horizontal swipe gesture to flip between the articles, but is still somewhat useable (swipe slowly to scroll), and most infoboxes look decent.

Download/save [the file](https://gist.githubusercontent.com/itkach/1eb0fbe7e65e8acc9d3c35b0e0b14851/raw/d973245dbf6bc323f45de81f4cbc627fa48a869e/infoboxfix3.css), add it with "+" button in "User Styles" in Settings, and then choose this style when viewing an article. If you want dark version, append content of [night.css](https://github.com/itkach/mw2slob/blob/master/mw2slob/css/night.css) to your css file. 

Let me know what you think.

**Comment by Shudushi** [comment]
Hello itkach!

Thank you for your infoboxfix.
I tried the CSS and find it very usefull as a workaround for the moment.

Regards

Shudushi

![Screenshot_20220622-091321_Aard 2](https://user-images.githubusercontent.com/61908206/174968363-efbf2917-121e-469c-8b85-3dcb08a5cbfd.jpg)
